### ISSUE TITLE
Can`t boot with fix blank screen 

### ISSUE THREAD

**Issue by arifth** [ferxiit/Y520-15IKBN-OpenCore#2]
Hi, thanks for your EFI , 
I face a problem with blank screen,even after i downloaded fix.zip file and reboot again ,
but it shows up on my external monitor somehow,
did a little research and tried skylake spoof id , but it get only 7mb of vram ,
any help will be greatly appreciated 

regard,arifth

**Comment by ferxiit** [comment]
Hi, can you tell me what graphic card do you have?

**Comment by arifth** [comment]
> Hi, can you tell me what graphic card do you have?

Hi, thanks for quick reply,

I have gtx1050ti, 
Btw, if i change device property>aapl ig platform id to 12345678, it will run but only detected 7mb of vram

**Comment by ferxiit** [comment]
Sorry, but I can't help you,
I tried to find some solution, but without real access to your laptop, I can't really do anything, because problems with graphic card and display are hard to resolve.
Try posting your issue on forum that is dedicated to Hackintosh, maybe there they will help you.

**Comment by arifth** [comment]
will do , thx for ur suggestion
